logging:
  path: ./logs

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:5000/eureka/}

server:
  port: ${PORT:8080}

---
spring:
  profiles: heroku
eureka:
  instance:
    hostname: judge
    nonSecurePort: 80

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
